import pygame
screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
WIDTH, HEIGHT = screen.get_size()

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

GRAVITY = 0.8
JUMP_SPEED = -20
PLAYER_SPEED = 8
PLATFORM_WIDTH = WIDTH * 0.08
PLATFORM_HEIGHT = HEIGHT * 0.02
PLAYER_SIZE = WIDTH * 0.05

ENEMY_SIZE = WIDTH * 0.03
ENEMY_SPEED = 2

PLATFORM_MIN_SPACING = int(PLATFORM_HEIGHT)
PLATFORM_MAX_SPACING = int(PLATFORM_HEIGHT * 5)
ENEMY_SPAWN_CHANCE = 0.1